# # fill the template according this example; use snake_case:
#[[http]]
#service_name = "cyco_app"
#swagger_url="https://api.next.cyco.fun/v1/docs/openapi.json"
#base_url="https://api.next.cyco.fun"
#relative_path_to_swagger="/v1/docs/openapi.json"
#
#
#[[http]]
#service_name = "service#2"
#swagger_url="http://example_host/some_another_api/exampleservise#2/swagger.json"
#base_url="http://5.63.153.31:8085/v1/"
